# Generated by Django 4.1.13 on 2024-05-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('buyingprice', models.IntegerField()),
                ('sellingprice', models.IntegerField()),
                ('totalstock', models.IntegerField()),
            ],
        ),
    ]
