# Generated by Django 4.1.13 on 2024-05-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coustomers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Coustomers',
        ),
    ]
