# Generated by Django 4.1.13 on 2024-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustomers', '0002_rename_member_coustomers'),
    ]

    operations = [
        migrations.AddField(
            model_name='coustomers',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coustomers',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
