# Generated by Django 4.1.13 on 2024-05-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coustomers', '0004_rename_coustomers_coustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coustomer',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coustomer',
            name='lastInvoice',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coustomer',
            name='totalDeu',
            field=models.IntegerField(null=True),
        ),
    ]
